/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppLayout {
    }
    interface AppNavigation {
        "logos": string[];
    }
    interface AppRoot {
    }
    interface AppScale {
    }
    interface AppSvgStrokeColored {
    }
    interface AppSvgStrokeVibrant {
    }
}
declare global {
    interface HTMLAppLayoutElement extends Components.AppLayout, HTMLStencilElement {
    }
    var HTMLAppLayoutElement: {
        prototype: HTMLAppLayoutElement;
        new (): HTMLAppLayoutElement;
    };
    interface HTMLAppNavigationElement extends Components.AppNavigation, HTMLStencilElement {
    }
    var HTMLAppNavigationElement: {
        prototype: HTMLAppNavigationElement;
        new (): HTMLAppNavigationElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppScaleElement extends Components.AppScale, HTMLStencilElement {
    }
    var HTMLAppScaleElement: {
        prototype: HTMLAppScaleElement;
        new (): HTMLAppScaleElement;
    };
    interface HTMLAppSvgStrokeColoredElement extends Components.AppSvgStrokeColored, HTMLStencilElement {
    }
    var HTMLAppSvgStrokeColoredElement: {
        prototype: HTMLAppSvgStrokeColoredElement;
        new (): HTMLAppSvgStrokeColoredElement;
    };
    interface HTMLAppSvgStrokeVibrantElement extends Components.AppSvgStrokeVibrant, HTMLStencilElement {
    }
    var HTMLAppSvgStrokeVibrantElement: {
        prototype: HTMLAppSvgStrokeVibrantElement;
        new (): HTMLAppSvgStrokeVibrantElement;
    };
    interface HTMLElementTagNameMap {
        "app-layout": HTMLAppLayoutElement;
        "app-navigation": HTMLAppNavigationElement;
        "app-root": HTMLAppRootElement;
        "app-scale": HTMLAppScaleElement;
        "app-svg-stroke-colored": HTMLAppSvgStrokeColoredElement;
        "app-svg-stroke-vibrant": HTMLAppSvgStrokeVibrantElement;
    }
}
declare namespace LocalJSX {
    interface AppLayout {
    }
    interface AppNavigation {
        "logos"?: string[];
    }
    interface AppRoot {
    }
    interface AppScale {
    }
    interface AppSvgStrokeColored {
    }
    interface AppSvgStrokeVibrant {
    }
    interface IntrinsicElements {
        "app-layout": AppLayout;
        "app-navigation": AppNavigation;
        "app-root": AppRoot;
        "app-scale": AppScale;
        "app-svg-stroke-colored": AppSvgStrokeColored;
        "app-svg-stroke-vibrant": AppSvgStrokeVibrant;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-layout": LocalJSX.AppLayout & JSXBase.HTMLAttributes<HTMLAppLayoutElement>;
            "app-navigation": LocalJSX.AppNavigation & JSXBase.HTMLAttributes<HTMLAppNavigationElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-scale": LocalJSX.AppScale & JSXBase.HTMLAttributes<HTMLAppScaleElement>;
            "app-svg-stroke-colored": LocalJSX.AppSvgStrokeColored & JSXBase.HTMLAttributes<HTMLAppSvgStrokeColoredElement>;
            "app-svg-stroke-vibrant": LocalJSX.AppSvgStrokeVibrant & JSXBase.HTMLAttributes<HTMLAppSvgStrokeVibrantElement>;
        }
    }
}
